# Generated by Django 6.1.1 on 2026-09-26 00:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coffee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="銘柄名"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="説明文")),
                ("is_active", models.BooleanField(default=True, verbose_name="販売中")),
            ],
            options={
                "verbose_name": "銘柄",
                "verbose_name_plural": "銘柄",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="問屋名")),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=100, verbose_name="担当者"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="電話番号"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="メール"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Web サイト")),
                ("memo", models.TextField(blank=True, verbose_name="メモ")),
                ("is_active", models.BooleanField(default=True, verbose_name="使う")),
            ],
            options={
                "verbose_name": "問屋",
                "verbose_name_plural": "問屋",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChoiceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sales_channel", "販売チャネル"),
                            ("process", "生産処理"),
                            ("rank", "ランク"),
                            ("certification", "認証・受賞"),
                            ("adjustment_reason", "在庫調整の理由"),
                        ],
                        max_length=32,
                        verbose_name="種類",
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="表示名")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="並び順"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="使う")),
            ],
            options={
                "verbose_name": "選択肢",
                "verbose_name_plural": "選択肢",
                "ordering": ["category", "sort_order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "label"), name="choice_unique_label"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GreenLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="ロット名")),
                ("purchased_on", models.DateField(verbose_name="仕入れ日")),
                (
                    "product_name",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="問屋の商品名"
                    ),
                ),
                (
                    "english_name",
                    models.CharField(blank=True, max_length=300, verbose_name="英文名"),
                ),
                (
                    "product_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="商品コード"
                    ),
                ),
                (
                    "product_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="商品ページの URL"
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="国")),
                (
                    "area",
                    models.CharField(blank=True, max_length=300, verbose_name="エリア"),
                ),
                (
                    "farm",
                    models.CharField(blank=True, max_length=200, verbose_name="農園名"),
                ),
                (
                    "producer",
                    models.CharField(blank=True, max_length=200, verbose_name="生産者"),
                ),
                (
                    "variety",
                    models.CharField(blank=True, max_length=200, verbose_name="品種"),
                ),
                (
                    "altitude",
                    models.CharField(blank=True, max_length=100, verbose_name="標高"),
                ),
                (
                    "crop_year",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="収穫年度"
                    ),
                ),
                (
                    "grade",
                    models.CharField(blank=True, max_length=50, verbose_name="等級"),
                ),
                (
                    "cupping_profile",
                    models.TextField(blank=True, verbose_name="カッピングプロファイル"),
                ),
                (
                    "cupping_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="カッピングスコア",
                    ),
                ),
                (
                    "packaging",
                    models.CharField(blank=True, max_length=100, verbose_name="包装"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="商品説明・備考"),
                ),
                (
                    "weight_g",
                    models.PositiveIntegerField(verbose_name="仕入れ重量（g）"),
                ),
                (
                    "price_yen",
                    models.PositiveIntegerField(verbose_name="仕入れ値（円・税抜）"),
                ),
                (
                    "extra_cost_yen",
                    models.PositiveIntegerField(
                        default=0, verbose_name="送料などの経費（円・税抜）"
                    ),
                ),
                ("memo", models.TextField(blank=True, verbose_name="メモ")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="表示する"),
                ),
                (
                    "certifications",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"category": "certification"},
                        related_name="+",
                        to="inventory.choiceoption",
                        verbose_name="認証・受賞",
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "process"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.choiceoption",
                        verbose_name="生産処理（精製方法）",
                    ),
                ),
                (
                    "rank",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"category": "rank"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.choiceoption",
                        verbose_name="ランク",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="green_lots",
                        to="inventory.supplier",
                        verbose_name="問屋",
                    ),
                ),
            ],
            options={
                "verbose_name": "生豆ロット",
                "verbose_name_plural": "生豆ロット",
                "ordering": ["-purchased_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("weight_g", models.PositiveIntegerField(verbose_name="内容量（g）")),
                (
                    "price_yen",
                    models.PositiveIntegerField(verbose_name="販売価格（円・税抜）"),
                ),
                (
                    "packaging_cost_yen",
                    models.PositiveIntegerField(
                        default=0, verbose_name="包材費（円・税抜）"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="販売中")),
                (
                    "coffee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="inventory.coffee",
                        verbose_name="銘柄",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "ordering": ["coffee__name", "weight_g"],
            },
        ),
        migrations.CreateModel(
            name="Roast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "roasted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="焙煎日時"
                    ),
                ),
                (
                    "roaster",
                    models.CharField(
                        blank=True,
                        default="手回し焙煎機",
                        max_length=100,
                        verbose_name="焙煎機",
                    ),
                ),
                ("input_g", models.PositiveIntegerField(verbose_name="投入量（g）")),
                (
                    "handpick_g",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ハンドピックで除いた量（g）"
                    ),
                ),
                (
                    "output_g",
                    models.PositiveIntegerField(verbose_name="焙煎後重量（g）"),
                ),
                (
                    "duration_s",
                    models.PositiveIntegerField(verbose_name="焙煎時間（秒）"),
                ),
                (
                    "first_crack_s",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="1ハゼ開始（秒）"
                    ),
                ),
                (
                    "second_crack_s",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="2ハゼ開始（秒）"
                    ),
                ),
                (
                    "heat_notes",
                    models.TextField(blank=True, verbose_name="火力・操作のメモ"),
                ),
                (
                    "roast_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("light", "ライト"),
                            ("cinnamon", "シナモン"),
                            ("medium", "ミディアム"),
                            ("high", "ハイ"),
                            ("city", "シティ"),
                            ("full_city", "フルシティ"),
                            ("french", "フレンチ"),
                            ("italian", "イタリアン"),
                        ],
                        max_length=20,
                        verbose_name="焙煎度",
                    ),
                ),
                ("memo", models.TextField(blank=True, verbose_name="メモ")),
                ("tasting_notes", models.TextField(blank=True, verbose_name="特徴")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="評価",
                    ),
                ),
                (
                    "tasted_on",
                    models.DateField(blank=True, null=True, verbose_name="試飲日"),
                ),
                (
                    "idempotency_key",
                    models.UUIDField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                (
                    "coffee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roasts",
                        to="inventory.coffee",
                        verbose_name="銘柄",
                    ),
                ),
                (
                    "green_lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roasts",
                        to="inventory.greenlot",
                        verbose_name="生豆ロット",
                    ),
                ),
            ],
            options={
                "verbose_name": "焙煎記録",
                "verbose_name_plural": "焙煎記録",
                "ordering": ["-roasted_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Adjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "adjusted_on",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="日付"
                    ),
                ),
                ("delta_g", models.IntegerField(verbose_name="増減量（g）")),
                ("memo", models.TextField(blank=True, verbose_name="メモ")),
                (
                    "idempotency_key",
                    models.UUIDField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        limit_choices_to={"category": "adjustment_reason"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.choiceoption",
                        verbose_name="理由",
                    ),
                ),
                (
                    "green_lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="inventory.greenlot",
                        verbose_name="生豆ロット",
                    ),
                ),
                (
                    "roast",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="inventory.roast",
                        verbose_name="焙煎記録",
                    ),
                ),
            ],
            options={
                "verbose_name": "在庫調整",
                "verbose_name_plural": "在庫調整",
                "ordering": ["-adjusted_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "sold_on",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="販売日"
                    ),
                ),
                (
                    "customer",
                    models.CharField(blank=True, max_length=200, verbose_name="販売先"),
                ),
                ("memo", models.TextField(blank=True, verbose_name="メモ")),
                (
                    "idempotency_key",
                    models.UUIDField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        limit_choices_to={"category": "sales_channel"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.choiceoption",
                        verbose_name="販売チャネル",
                    ),
                ),
            ],
            options={
                "verbose_name": "販売",
                "verbose_name_plural": "販売",
                "ordering": ["-sold_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="数量")),
                (
                    "unit_price_yen",
                    models.PositiveIntegerField(verbose_name="単価（円・税抜）"),
                ),
                (
                    "packaging_cost_yen",
                    models.PositiveIntegerField(
                        default=0, verbose_name="包材費（円・税抜）"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_items",
                        to="inventory.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.sale",
                        verbose_name="販売",
                    ),
                ),
            ],
            options={
                "verbose_name": "販売明細",
                "verbose_name_plural": "販売明細",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("weight_g", models.PositiveIntegerField(verbose_name="重さ（g）")),
                (
                    "roast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="inventory.roast",
                        verbose_name="焙煎記録",
                    ),
                ),
                (
                    "sale_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="inventory.saleitem",
                        verbose_name="販売明細",
                    ),
                ),
            ],
            options={
                "verbose_name": "引当",
                "verbose_name_plural": "引当",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight_g__gte", 1)), name="product_weight_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("coffee", "weight_g"), name="product_unique_weight"
            ),
        ),
        migrations.AddConstraint(
            model_name="roast",
            constraint=models.CheckConstraint(
                condition=models.Q(("input_g__gt", 0)), name="roast_input_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="roast",
            constraint=models.CheckConstraint(
                condition=models.Q(("output_g__gt", 0)), name="roast_output_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="roast",
            constraint=models.CheckConstraint(
                condition=models.Q(("output_g__lt", models.F("input_g"))),
                name="roast_output_lt_input",
            ),
        ),
        migrations.AddConstraint(
            model_name="roast",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_s__gt", 0)),
                name="roast_duration_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="roast",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("first_crack_s__isnull", True),
                    ("first_crack_s__lt", models.F("duration_s")),
                    _connector="OR",
                ),
                name="roast_first_crack_lt_duration",
            ),
        ),
        migrations.AddConstraint(
            model_name="roast",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("second_crack_s__isnull", True),
                    ("second_crack_s__lt", models.F("duration_s")),
                    _connector="OR",
                ),
                name="roast_second_crack_lt_duration",
            ),
        ),
        migrations.AddConstraint(
            model_name="roast",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("first_crack_s__isnull", True),
                    ("second_crack_s__isnull", True),
                    ("first_crack_s__lt", models.F("second_crack_s")),
                    _connector="OR",
                ),
                name="roast_first_crack_lt_second",
            ),
        ),
        migrations.AddConstraint(
            model_name="roast",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rating__isnull", True),
                    models.Q(("rating__gte", 1), ("rating__lte", 5)),
                    _connector="OR",
                ),
                name="roast_rating_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="adjustment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("green_lot__isnull", False), ("roast__isnull", True)),
                    models.Q(("green_lot__isnull", True), ("roast__isnull", False)),
                    _connector="OR",
                ),
                name="adjustment_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="adjustment",
            constraint=models.CheckConstraint(
                condition=models.Q(("delta_g", 0), _negated=True),
                name="adjustment_delta_nonzero",
            ),
        ),
        migrations.AddConstraint(
            model_name="saleitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="sale_item_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight_g__gte", 1)),
                name="allocation_weight_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="greenlot",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight_g__gt", 0)),
                name="green_lot_weight_positive",
            ),
        ),
    ]
